<a href="https://colab.research.google.com/github/Shalini006Minj/Airport-Cabs-Data-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.shape
# output 2 row and 3 columns

(2, 3)

# Methods in numpy

While manually creating NumPy arrays is useful for small examples, there are many inbuilt NumPy methods for creating arrays that can save you a lot of time and effort when working with larger datasets

In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a = np.ones([2,6])
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = np.zeros([2,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a = np.arange(2,50,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
# 2D array with arange()
a = np.arange(2,50,2).reshape(6,4)
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
# np.linspace() : s a function in NumPy that returns an array of evenly spaced values over a specified range
a = np.linspace(0,50,endpoint=False) # in here endpoint i.e number 50 is excluded
print(a)

b = np.linspace(0,50) # in here number 50 is included
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


In [ ]:
# np.eye() : It returns a matrix with ones on the diagonal and zeros elsewhere, it is commonly used in linear algebra
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Find minimum ,maximum ,sum and mean data in array

In [ ]:
a = np.arange(5,25)
print(a)
print(f"max:{a.max()}")
print(f"min:{a.min()}")
print(f"sum:{a.sum()}")
print(f"mean:{a.mean()}")

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
max:24
min:5
sum:290
mean:14.5


# Indexing

In [ ]:
# 1D
b = np.array([1,2,3,4])
b[0]

1

In [ ]:
b[2]+b[3]

7

In [ ]:
# 2D - its like rows and columns
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"2nd element in the 1st row is: {c[0,1]}")

2nd element in the 1st row is: 2


In [ ]:
print(f"last element in the 2nd row is: {c[1,4]}")

last element in the 2nd row is: 10


In [ ]:
# 3D
d = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(f"2nd element of the 3rd row is {d[0,2,2]}")

2nd element of the 3rd row is 13


In [ ]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x.shape
x[1,1,1]


11

slicing -
taking elements from one given index to another index.

In [ ]:
# [start:end:steps] - steps in optional
a = np.array([1,2,3,4,5,6,7,8,9])
a[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
print(f"start from 4th index and go till the end: {a[4:]}")

start from 4th index and go till the end: [5 6 7 8 9]


In [ ]:
print(f"start till the index 4th: {a[:4]}")

start till the index 4th: [1 2 3 4]


In [ ]:
# negative slicing
print(f"reverse slicing: {a[::-1]}")

reverse slicing: [9 8 7 6 5 4 3 2 1]


In [ ]:
print(f"start from -6 index till the end: {a[-6:-1]}")

start from -6 index till the end: [4 5 6 7 8]


In [ ]:
print(f"every alternative number: {a[::2]}")

every alternative number: [1 3 5 7 9]


slicing in 2D

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a[1,0]

6

In [ ]:
a[1,1:4]

array([7, 8, 9])

In [ ]:
print(f"all elements from 1st row and all elements from the index 2nd in the 1st row: {a[0,0:],a[1,2:]}")

all elements from 1st row and all elements from the index 2nd in the 1st row: (array([1, 2, 3, 4, 5]), array([ 8,  9, 10]))


In [ ]:
a[0:2,3]

array([4, 9])

In [ ]:
a[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

Numpy array datatypes


1.   integer - i
2.   boolean - b
3.   unsigned integer - u
4.   float - f
5.   complex float - c
6.   timedelta - m
7.   datetime - M
8.   object - O
9.   strings - S
10.  unicode string - U
11.  memory - V



In [ ]:
# checking the data type
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

In [ ]:
# checking the data type of string
b = np.array(['apple','banana','cherry'])
b.dtype

dtype('<U6')

In [ ]:
# creating array w/ a defined datatype
a = np.array([1,2,3,4],dtype='S')
print(a.dtype,a) # b in the output indicate byte string

|S1 [b'1' b'2' b'3' b'4']


In [ ]:
# create an array w/ datatype of 4byte integer
a = np.array([1,2,3,4],dtype='i4')
print(a.dtype,a) #8*4=32

int32 [1 2 3 4]


In [ ]:
# we cannot convert string to integer
a = np.array(['1','2','3'],dtype='i')
print(a.dtype,a)

int32 [1 2 3]


In [ ]:
"""
a = np.array(['a','2','3'],dtype='i')
print(a.dtype,a)

ValueError                                Traceback (most recent call last)
<ipython-input-36-c7c8557ed39a> in <cell line: 1>()
----> 1 a = np.array(['a','2','3'],dtype='i')
      2 print(a.dtype,a)

ValueError: invalid literal for int() with base 10: 'a'
"""

"\na = np.array(['a','2','3'],dtype='i')\nprint(a.dtype,a)\n\nValueError                                Traceback (most recent call last)\n<ipython-input-36-c7c8557ed39a> in <cell line: 1>()\n----> 1 a = np.array(['a','2','3'],dtype='i')\n      2 print(a.dtype,a)\n\nValueError: invalid literal for int() with base 10: 'a'\n"

In [ ]:
# converting a datatype on existing array -- astype()
# we must do this to convert float to integer use astype()
a = np.array([1.1,2.1,3.1,4.1])
a1 = a.astype('i')
print(a1.dtype,a1)

int32 [1 2 3 4]


In [ ]:
a = np.array([1.1,2.1,3.1,4.1,5.1])
a2 = a.astype(int) # can write int as well
print(a2.dtype,a2)

int64 [1 2 3 4 5]


In [ ]:
# converting datatype from integer to boolean
a = np.array([1,0,3])
a3 = a.astype(bool) # can write int as well
print(a3.dtype,a3)

bool [ True False  True]


numpy copy and view




In [ ]:
# copy()
a = np.array([1,2,3,4,5])
a1 = a.copy()
print("a1",a1)

a1 [1 2 3 4 5]


In [ ]:
# view()
a = np.array([1,2,3,4,5])
a2 = a.view()
a2[0] = 42
a2

array([42,  2,  3,  4,  5])

Numpy shapes

shape of an array?

elements inside the dimensions are called shapes of an array.

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

# 2 dimension and 4 elements in each dimensions

(2, 4)

In [ ]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
b.shape

"""
1: There is 1 block of arrays (the outermost dimension).
3: There are 3 rows inside the block.
4: Each row contains 4 elements.
"""

'\n1: There is 1 block of arrays (the outermost dimension).\n3: There are 3 rows inside the block.\n4: Each row contains 4 elements.\n'

In [ ]:
c = np.array([1,2,3,4,5],ndmin=5)
print(c.shape,c)

(1, 1, 1, 1, 5) [[[[[1 2 3 4 5]]]]]


reshaping of array - add, remove or modify elements

In [ ]:
# from 1D to 2D
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 =a.reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 1D to 3D
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a2 =a.reshape(2,3,2)
a2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
# unknown dimension reshaping - only one unknown dimesion is allowed
a = np.array([1,2,3,4,5,6,7,8])
a1 = a.reshape(2,2,-1) # -1 will calculate itself
a1


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# flattening the array by converting multidimensional array into 1D
a = np.array([[1,2,3],[4,5,6]])
a1 = a.reshape(-1) # -1 will change anything to 1D
a1

array([1, 2, 3, 4, 5, 6])

there are alot of functions for changing the shapes of an array. like flatten, ravel and rearrange(rot90, fliplr,flipud). these are mainly used in advanced numpy.

Numpy array iterating

In [ ]:
# loop in 1D
a = np.array([1,2,3])
for i in a:
  print(i, end=" ")

1 2 3 

In [ ]:
# loop in 2D
a = np.array([[1,2,3],[4,5,6]])
for i in a:
  print(i)

[1 2 3]
[4 5 6]


In [ ]:
# scalar element- iterate on each element
a = np.array([[1,2,3],[4,5,6]])
for i in a:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
# loop in 3D
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for i in a:
  for j in i:
    for k in j:
      print(k,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
# iterating using 'nditer()' function
# a helping function

# iterate on each scalar element
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for i in np.nditer(a):
  print(i,end=" ")

1 2 3 4 5 6 7 8 

In [ ]:
# iterate w/ different step sizes
a = np.array([[1,2,3,10],[4,5,6,20]])
for i in np.nditer(a[:,::2]):
  print(i,end=" ")

1 3 4 6 

#**Joining two or more arrays together**

In [ ]:
a = np.array([1,2,3])
a1 = np.array([4,5,6])
a2 = np.concatenate((a,a1))
a2

array([1, 2, 3, 4, 5, 6])


Imp. things to remember

---


*   axis = 0 [column]
*   axis = 1 [row]



In [ ]:
# joining of 2D along w/ rows(axis=1)
a = np.array([[1,2],[3,4]])
a1 = np.array([[5,6],[7,8]])
a2 = np.concatenate((a,a1), axis = 1)
a2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.array([[1,2],[3,4]])
a1 = np.array([[5,6],[7,8]])
a2 = np.concatenate((a,a1), axis = 0)
a2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# joining array using stack() function
a = np.array([1,2,3])
a1 = np.array([4,5,6])
a2 = np.stack((a,a1),axis=1)
a2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# stacking along with rows: hstack() for horizontal joining
a = np.array([1,2,3])
a1 = np.array([4,5,6])
a2 = np.hstack((a,a1))
a2

array([1, 2, 3, 4, 5, 6])

In [ ]:
# stacking with column
a = np.array([1,2,3])
a1 = np.array([4,5,6])
a2 = np.vstack((a,a1))
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking along with height(dept)
a = np.array([1,2,3])
a1 = np.array([4,5,6])
a2 = np.dstack((a,a1))
a2

array([[[1, 4],
        [2, 5],
        [3, 6]]])

#Split array

In [ ]:
# we use array_split() function

# splitting in three parts
z = np.array([1,2,3,4,5,6])
z1 = np.array_split(z,3)
z1

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
x = np.array([1,2,3,4,5,6,7,8])
x1 = np.array_split(x,4)
x1

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [ ]:
i = np.array([1,2,3,4,5,6])
i1 = np.array_split(i,4)
i1

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:
z = np.array([1,2,3,4,5,6])
z1 = np.array_split(z,3)
z1[0] # in case we want to print only specific index elements

array([1, 2])

In [ ]:
# 2D splitting
# splitting one 2D into three different 2Ds
z = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
z1 = np.array_split(z,3)
z1

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [ ]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
z1 = np.array_split(z,3)
z1

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
# splitting 2D into three 2D, along w/ rows
z = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
z1 = np.array_split(z,3,axis=1)
print(z1,end=" ")

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])] 

In [ ]:
# alternate solution using hsplit(), which is the spp. of hstack()
z = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
z1 = np.hsplit(z,3)
print(z1,end=" ")


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])] 

# searching array - using where()



In [ ]:
a = np.array([1,2,3,4,5,4,4])
a1 = np.where(a == 4)
a1

(array([3, 5, 6]),)

In [ ]:
# find the indexes where the values are even numbers
a = np.array([1,2,3,4,5,6,7,8])
a1 = np.where(a % 2 == 0)
a1

(array([1, 3, 5, 7]),)

In [ ]:
# find the indexes where the values are odd numbers
a = np.array([1,2,3,4,5,6,7,8])
a1 = np.where(a % 2 != 0)
a1

(array([0, 2, 4, 6]),)

# searchsorted()

perform binary search in array

In [ ]:
# find the index where the value 7 should be inserted

a = np.array([6,7,8,9])
a1 = np.searchsorted(a,7)
a1

1

In [ ]:
# search from the right side

b = np.array([6,7,8,9])
b1 = np.searchsorted(b,7, side='right')
b1

2

In [ ]:
# lets search multiple values
"""
c = np.array([1,3,5,7])
c1 = np.searchsorted(c, [2,4,6])
c1
"""

'\nc = np.array([1,3,5,7])\nc1 = np.searchsorted(c, [2,4,6])\nc1\n'

# sorting

In [ ]:
# sort()

a = np.array([3,2,0,1])
np.sort(a)

array([0, 1, 2, 3])

In [ ]:
# string sorting

a = np.array(['banana','cherry','apple'])
np.sort(a)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [ ]:
# boolean sorting
a = np.array([True, False, True])
np.sort(a)

array([False,  True,  True])

In [ ]:
# 2D sorting, same goes for 3D array

a = np.array([[3,2,4],[5,0,1]])
np.sort(a)

array([[2, 3, 4],
       [0, 1, 5]])

# filtering

In [ ]:
a = np.array([41,42,43,44])
a1 = [True,False,True,False]
final_a = a[a1]
final_a

array([41, 43])

In [ ]:
# we'll create a filter array, it will return values >42
a = np.array([41,42,43,44])
empty_a = []
for i in a:
  if i > 42:
    empty_a.append(True)
  else:
    empty_a.append(False)
a_new = a[empty_a]
print(f"empty_a: {empty_a}")
print(f"a_new: {a_new}")

empty_a: [False, False, True, True]
a_new: [43 44]


In [ ]:
# alternative method

a = np.array([41,42,43,44])
empty_a = a > 42
a_new = a[empty_a]
print(f"empty_a: {empty_a}")
print(f"a_new: {a_new}")

empty_a: [False False  True  True]
a_new: [43 44]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
empty_a = a%2==0
a_new = a[empty_a]
print(f"empty_a: {empty_a}")
print(f"a_new: {a_new}")

empty_a: [False  True False  True False  True False  True False  True]
a_new: [ 2  4  6  8 10]


# random number

In [ ]:
from numpy import random

In [ ]:
# 0 to 100 random number generation
a = random.randint(100)
a

80

In [ ]:
# float number generation
a = random.rand(10)
a

# if we do no provide any value it will by default give value from 0 to 1

array([0.85022753, 0.65975442, 0.31981779, 0.44071461, 0.42254305,
       0.96952103, 0.65996655, 0.25390636, 0.82947038, 0.95129587])

In [ ]:
# generate random array
# 1D containing 5 random int from 0-100

a = random.randint(100, size = (5))
a

array([ 1,  9, 55, 43, 14])

In [ ]:
# 2D containing 3 rows with 5 random int elements from 0-100

a = random.randint(100, size=(3,5))
a

array([[97, 61,  7, 29, 12],
       [25, 14, 20, 32, 81],
       [90, 27, 70, 47, 27]])

In [ ]:
# 1D containing 5 random float

a = random.rand(5)
a

array([0.89527642, 0.19733346, 0.24990751, 0.77978582, 0.74203202])

In [ ]:
# 2D containing 3 rows and 5 random float

a = random.rand(3,5)
a

array([[0.513209  , 0.26429972, 0.9249711 , 0.11436757, 0.39715769],
       [0.46329241, 0.72893239, 0.4694692 , 0.13726511, 0.52597519],
       [0.39354843, 0.71061038, 0.38478408, 0.47491057, 0.76035268]])

In [ ]:
# picking random numbers from an 1D array using choice()

a = random.choice([3,5,7,9,6,4])
a

7

In [ ]:
# picking from 1D array and changing into 2D array with 3 rows and 5 elements

a = random.choice([3,5,7,9,6,4],size=(3,5))
a

array([[6, 5, 5, 9, 7],
       [7, 3, 4, 4, 6],
       [9, 4, 6, 4, 5]])

# Arithmetic operations

In [ ]:
a = np.arange(1,6)
a
print(a+2)
print(a*2)
print(a/2)
print(a//2)
print(a%2)


[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]


# Broadcasting

Broadcasting in NumPy refers to the ability of NumPy to perform arithmetic operations on arrays of different shapes in a way that automatically expands their dimensions to make them compatible. This eliminates the need to manually resize arrays, allowing for efficient vectorized operations.

In [ ]:
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# examples

# 1. Adding a scalar value with the array

a = np.array([10,20,30])
result = a + 5
result

array([15, 25, 35])

In [ ]:
# 2. Adding two arrays of different shapes

a = np.array([[10,20],[30,40],[50,60]]) # size (3,2)
a1 = np.array([2,4]) # size (2,)
result = a+a1
result

array([[12, 24],
       [32, 44],
       [52, 64]])

In [ ]:
# 3. Adding a column vector with a matrix
a = np.array([[10,20,30],[40,50,60]])
a1 = np.array([[10],[20]])
result = a+a1
result

array([[20, 30, 40],
       [60, 70, 80]])

In [ ]:
#Setting a value with index range (Broadcasting)

a = np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
a_copy = a.copy()
print(f"Before brodcasting{a_copy}")

a_copy[0:5] = 1000
print(f"After broadcasting{a_copy}")

Before brodcasting[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
After broadcasting[1000 1000 1000 1000 1000    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25]


# Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [ ]:
# Print numbers >5
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [ ]:
# instead of 'and' we use '&' in numpy with parentheses
# Similarly instead of "or" we use "|" in numpy with parentheses else there will be an error

a[(a<15) & (a>10)]

array([11, 12, 13, 14])

In [ ]:
a[(a<15) | (a>10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])